baseURL = "https://17tay.pages.dev/"
languageCode = "en-us"
title = "17tay"
theme = "PaperMod"
[pagination]
  pagerSize = 10
enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false
defaultContentLanguage = "en"
disqusShortname = ""

[params]
  env = "production"
  ShowImage = true
  title = "17tay"
  mainSections = ["posts"]
  description = "Blog técnico de ciberseguridad, pentesting y programación"
  author = "17tay"
  showImageInList = true
  showImageInSingle = true
  hideFooter = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  showFeaturedPosts = true
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowWordCount = true
  ShowRecentPosts = true
  recentPostCount = 3

  [params.profileMode]
    enabled = true
    title = "17tay"
    subtitle = "Red Teamer en progreso. Blog de pentesting, malware, CTFs y más."
    imageUrl = "images/tay.png"
    imageTitle = "Mi avatar"
    buttons = [
      { name = "Ver mis posts", url = "/posts/"},
      { name = "GitHub", url = "https://github.com/17tayyy" },
      { name = "Hack The Box", url = "https://app.hackthebox.com/profile/2019721" },
      { name = "Twitter", url = "https://x.com/17tayyy"},
      { name = "Contacto", url = "mailto:oscarfdst@proton.me" }
    ]

  [params.homeInfoParams]
    Title = "Bienvenido al blog de 17tay"
    Content = """
    Aquí encontrarás artículos técnicos, writeups, herramientas ofensivas, y mis avances en el mundillo ciber.
    """

[params.assets]
  disableFingerprinting = true
  customJS = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/js/all.min.js"]

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
